### ISSUE TITLE
Unable to tap while showing JSImagePickerController in modally presented VC

### ISSUE THREAD

**Issue by WeeTom** [jacobsieradzki/JSImagePickerController#1]
See, I happen to use JSIPC in a modally presented VC, and found it unable to tap, anywhere on the screen.
By using Reveal, I fount a UITrasnsitionView above. Guess it is the reason why. So any solutions would help?

**Comment by jacobsieradzki** [comment]
Could you show me your code of how you try to show the JSImagePickerController?

**Comment by WeeTom** [comment]
Well..Like this
Simply, I rewrite the demo code

```
- (void)showBtnWasPressed:(id)sender {
    UIViewController *vc = [[UIViewController alloc] init];
    UINavigationController *nav = [[UINavigationController alloc] initWithRootViewController:vc];
    [self presentViewController:nav animated:YES completion:^{
        JSImagePickerViewController *imagePicker = [[JSImagePickerViewController alloc] init];
        imagePicker.delegate = self;
        [imagePicker showImagePickerInController:vc animated:YES];
    }];
}
```

**Comment by Yaou** [comment]
same situation with my project.

**Comment by Yaou** [comment]
btw, it is only happened with ios8.

**Comment by Yaou** [comment]
fix this with follow code:

if ([[[UIDevice currentDevice] systemVersion] floatValue]>=8.0) {
            self.modalPresentationStyle = UIModalPresentationOverCurrentContext;
} else {
           self.modalPresentationStyle = UIModalPresentationCustom;
}

instead of 
self.modalPresentationStyle = UIModalPresentationCustom;

in function showImagePickerInController

but, one more problem, it show the black background when present the picker in ios7.

**Comment by WeeTom** [comment]
@Yaou Thanks~Really nice job!
@jacobsieradzki plz also take some time and fix it up on your repo thanks!
