### ISSUE TITLE
Cannot run the demo.

### ISSUE THREAD

**Issue by moyoteg** [jacobsieradzki/JSImagePickerController#8]
I tried to run the demo but it fails with multiple errors. Do you know why that it?

<img width="260" alt="screen shot 2015-08-13 at 10 22 30 am" src="https://cloud.githubusercontent.com/assets/574112/9255237/32ac1976-41a5-11e5-97d2-a0bca4930cfc.png">

**Comment by jacobsieradzki** [comment]
Yes, I tried to merge some pull requests and there were conflicts and errors that I haven't had time yet to fix, I will try to do it soon.

**Comment by jacobsieradzki** [comment]
All errors have been fixed today.
